steps:
  # 1. Build the JAR
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']

  # 2. Deploy to App Engine flexible environment
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--image-url=gcr.io/$PROJECT_ID/spring-boot-mongodb-reactive:$COMMIT_SHA']

# Configure environment variables for App Engine
env:
  - 'JAVA_VERSION=17'

# Specify runtime and environment for App Engine
runtime: java
env: flex

# Define handlers for App Engine routes
handlers:
  - url: /.*
    script: this field is required, but ignored

# Set runtime configuration for App Engine
runtime_config:
  jdk: openjdk17
